// swift-tools-version: 6.2

import Foundation
import PackageDescription

let package = Package(
    name: "sing-swift",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v26),
    ],
    products: [
        .library(
            name: "sing-swift",
            targets: ["sing-swift"],
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.92.0"),
        .package(url: "https://github.com/apple/swift-nio-transport-services.git", from: "1.26.0"),
        .package(url: "https://github.com/apple/swift-nio-http2.git", from: "1.39.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.36.0"),
        .package(url: "https://github.com/apple/swift-nio-extras.git", from: "1.31.2"),
        .package(url: "https://github.com/apple/swift-configuration.git", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.8.0"),
        .package(url: "https://github.com/apple/swift-async-algorithms.git", from: "1.1.1"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "4.2.0"),
        .package(url: "https://github.com/apple/swift-certificates.git", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-async-dns-resolver.git", from: "0.5.0"),
        .package(url: "https://github.com/apple/swift-atomics.git", from: "1.2.0"),
        .package(url: "https://github.com/apple/swift-collections.git", from: "1.1.4"),
        .package(url: "https://github.com/apple/swift-system.git", from: "1.6.3"),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.5.1"),
        .package(url: "https://github.com/sonqyau/swift-nio-ssh.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-nio-oblivious-http.git", from: "0.7.0"),
        .package(url: "https://github.com/apple/swift-algorithms.git", from: "1.2.0"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.7.0"),
        .package(url: "https://github.com/apple/swift-numerics.git", from: "1.0.0"),
        .package(url: "https://github.com/swift-server/swift-service-lifecycle.git", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-metrics.git", from: "2.5.0"),
        .package(url: "https://github.com/apple/swift-asn1.git", from: "1.5.1"),
        .package(url: "https://github.com/apple/swift-http-structured-headers.git", from: "1.6.0"),
        .package(url: "https://github.com/apple/swift-metrics-extras.git", from: "0.3.2"),
        .package(url: "https://github.com/apple/swift-statsd-client.git", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-binary-parsing.git", from: "0.0.1"),
        .package(url: "https://github.com/apple/swift-service-context.git", from: "1.2.1"),
        .package(url: "https://github.com/apple/swift-service-discovery.git", from: "1.4.0"),
        // .package(url: "https://github.com/apple/swift-protobuf.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-ntp.git", from: "0.3.1"),
        // .package(url: "https://github.com/apple/swift-distributed-actors.git", branch: "main"),
        // .package(url: "https://github.com/apple/swift-cluster-membership.git", from: "0.3.2"),
        // .package(url: "https://github.com/apple/swift-homomorphic-encryption.git", branch: "main"),
        // .package(url: "https://github.com/apple/swift-profile-recorder.git", from: "0.3.10"),
    ],
    targets: [
        .target(
            name: "sing-swift",
            dependencies: [
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOEmbedded", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "_NIOConcurrency", package: "swift-nio"),
                .product(name: "NIOTLS", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOConcurrencyHelpers", package: "swift-nio"),
                .product(name: "NIOFoundationCompat", package: "swift-nio"),
                .product(name: "NIOWebSocket", package: "swift-nio"),
                .product(name: "NIOTestUtils", package: "swift-nio"),
                .product(name: "_NIOFileSystem", package: "swift-nio"),
                .product(name: "_NIOFileSystemFoundationCompat", package: "swift-nio"),
                .product(name: "NIOTransportServices", package: "swift-nio-transport-services"),
                .product(name: "NIOHTTP2", package: "swift-nio-http2"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "NIOExtras", package: "swift-nio-extras"),
                .product(name: "NIOSOCKS", package: "swift-nio-extras"),
                .product(name: "NIOHTTPCompression", package: "swift-nio-extras"),
                .product(name: "NIOHTTPTypes", package: "swift-nio-extras"),
                .product(name: "NIOHTTPTypesHTTP1", package: "swift-nio-extras"),
                .product(name: "NIOHTTPTypesHTTP2", package: "swift-nio-extras"),
                .product(name: "NIOResumableUpload", package: "swift-nio-extras"),
                .product(name: "NIOHTTPResponsiveness", package: "swift-nio-extras"),
                .product(name: "NIOCertificateReloading", package: "swift-nio-extras"),
                .product(name: "Configuration", package: "swift-configuration"),
                .product(name: "Logging", package: "swift-log"),
                .product(name: "InMemoryLogging", package: "swift-log"),
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                .product(name: "Crypto", package: "swift-crypto"),
                .product(name: "_CryptoExtras", package: "swift-crypto"),
                .product(name: "X509", package: "swift-certificates"),
                .product(name: "AsyncDNSResolver", package: "swift-async-dns-resolver"),
                .product(name: "Atomics", package: "swift-atomics"),
                .product(name: "BasicContainers", package: "swift-collections"),
                .product(name: "BitCollections", package: "swift-collections"),
                .product(name: "ContainersPreview", package: "swift-collections"),
                .product(name: "DequeModule", package: "swift-collections"),
                .product(name: "HashTreeCollections", package: "swift-collections"),
                .product(name: "HeapModule", package: "swift-collections"),
                .product(name: "OrderedCollections", package: "swift-collections"),
                .product(name: "_RopeModule", package: "swift-collections"),
                .product(name: "TrailingElementsModule", package: "swift-collections"),
                .product(name: "Collections", package: "swift-collections"),
                .product(name: "SystemPackage", package: "swift-system"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "HTTPTypesFoundation", package: "swift-http-types"),
                .product(name: "NIOSSH", package: "swift-nio-ssh"),
                .product(name: "ObliviousDoH", package: "swift-nio-oblivious-http"),
                .product(name: "ObliviousX", package: "swift-nio-oblivious-http"),
                .product(name: "ObliviousHTTP", package: "swift-nio-oblivious-http"),
                .product(name: "Algorithms", package: "swift-algorithms"),
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "Numerics", package: "swift-numerics"),
                .product(name: "ComplexModule", package: "swift-numerics"),
                .product(name: "RealModule", package: "swift-numerics"),
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
                .product(name: "UnixSignals", package: "swift-service-lifecycle"),
                .product(name: "CoreMetrics", package: "swift-metrics"),
                .product(name: "Metrics", package: "swift-metrics"),
                .product(name: "SwiftASN1", package: "swift-asn1"),
                .product(name: "StructuredFieldValues", package: "swift-http-structured-headers"),
                .product(name: "RawStructuredFieldValues", package: "swift-http-structured-headers"),
                .product(name: "SystemMetrics", package: "swift-metrics-extras"),
                .product(name: "StatsdClient", package: "swift-statsd-client"),
                .product(name: "BinaryParsing", package: "swift-binary-parsing"),
                .product(name: "ServiceContextModule", package: "swift-service-context"),
                .product(name: "ServiceDiscovery", package: "swift-service-discovery"),
                // .product(name: "SwiftProtobuf", package: "swift-protobuf"),
                // .product(name: "SwiftProtobufPluginLibrary", package: "swift-protobuf"),
                .product(name: "NTPClient", package: "swift-ntp"),
                // .product(name: "DistributedCluster", package: "swift-distributed-actors"),
                // .product(name: "ClusterMembership", package: "swift-cluster-membership"),
                // .product(name: "SWIM", package: "swift-cluster-membership"),
                // .product(name: "HomomorphicEncryption", package: "swift-homomorphic-encryption"),
                // .product(name: "ModularArithmetic", package: "swift-homomorphic-encryption"),
                // .product(name: "HomomorphicEncryptionProtobuf", package: "swift-homomorphic-encryption"),
                // .product(name: "_HomomorphicEncryptionExtras", package: "swift-homomorphic-encryption"),
                // .product(name: "PrivateInformationRetrieval", package: "swift-homomorphic-encryption"),
                // .product(name: "PrivateNearestNeighborSearch", package: "swift-homomorphic-encryption"),
                // .product(name: "ApplicationProtobuf", package: "swift-homomorphic-encryption"),
                // .product(name: "ProfileRecorder", package: "swift-profile-recorder"),
                // .product(name: "ProfileRecorderServer", package: "swift-profile-recorder"),
            ],
            path: "Sources",
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("ExistentialAny"),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ApproachableConcurrency"),
                .unsafeFlags(["-cross-module-optimization"],
                             .when(configuration: .release)),
            ],
        ),
    ],
)
